### PR TITLE
Add Winget Releaser workflow

### LINKED ISSUE #141: Publish to Windows Package Manager (WinGet)
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
With every new release of ViGEmBus, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

Same can be done for HidHide.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them. This is in line with the PR in HidHide (https://github.com/ViGEm/HidHide/pull/80).

Before merging this:
- Follow the steps in https://github.com/ViGEm/HidHide/pull/80. See that PR for the rest of the information.

Resolves #141

### CODE REVIEW

**Comment by sitiom** [comment]
@nefarius bump since you released a new version

**Comment by sitiom** [comment]
https://github.com/ViGEm/winget-pkgs doesn't exist?

**Comment by nefarius** [comment]
It does now 😇

**Comment by sitiom** [comment]
Ok, now just make sure you have done all the prerequisites mentioned in https://github.com/ViGEm/ViGEmBus/pull/142#issue-1325576798

**Comment by nefarius** [comment]
Continuing it!

**Comment by sitiom** [comment]
Also install the [Pull](https://github.com/apps/pull) app on the [winget-pkgs fork](https://github.com/ViGEm/winget-pkgs) so that it is regularly updated.

**Pull request merged**
