### PR TITLE
Fix bug, if the plugin fails, the `VIGEM_TARGETS_MAX` device will be created.

### PR DESCRIPTION
**Pull request by MiroKaku**
**Hi,**

**Describe the bug**
Starting from the fifth ‘plugin’, countless devices will be created. (VIGEM_TARGETS_MAX 0xFFFF)

**To Reproduce**
Run this:
```C
int main()
{
    static const auto target_number = 5;

    const auto client = vigem_alloc();
    auto ret = vigem_connect(client);
    if (!VIGEM_SUCCESS(ret))
    {
        std::cerr << "vigem_connect() failed! ret: " << std::hex << ret << std::endl;
    }

    PVIGEM_TARGET targets[target_number] = { nullptr };

    for (auto i = 0u; i < target_number; ++i)
    {
        targets[i] = vigem_target_x360_alloc();

        ret = vigem_target_add(client, targets[i]);

        std::cerr << "vigem_target_add(" << std::dec << i << ") ret: " << std::hex << ret << std::endl;
    }

    // pause
    (void)getchar();

    for (auto i = 0u; i < target_number; ++i)
    {
        vigem_target_remove(client, targets[i]);
        vigem_target_free(targets[i]);
    }

    vigem_free(client);

    return 0;
}
```

**Expected behavior**
Create 4 or 5 devices, But created countless. (VIGEM_TARGETS_MAX 0xFFFF)

**Screenshots**
image

**System details (please complete the following information):**
 - OS: [Windows 10 1903]
 - Driver Version: [commit 288222f]

### CODE REVIEW

**Comment by nefarius** [comment]
Thanks, I haven't forgotten to address this, just wanna give it the appropriate time to dig into the proposed changes. Bear with me please.

**Comment by MeeSong** [comment]
Don't worry, I understand. Thank you for open source this project. 👍

**Comment by MiroKaku** [comment]
Don't worry, I understand. Thank you for open source this project. 👍

**Comment by nefarius** [comment]
I can not reproduce the issue described on the [latest development branch](https://github.com/ViGEm/ViGEmBus/tree/v1.17-experimental).

**Comment by nefarius** [comment]
Did further testing, I identified another issue, I can fix it in the upcoming v1.17 branch, sorry for the PR, bad timing 😅

**Comment by MeeSong** [comment]
on the master branch 😅

**Comment by nefarius** [comment]
The master branch is quite outdated though 🙁

**Comment by MeeSong** [comment]
Oh! I'm sorry. 😅

**Comment by nefarius** [comment]
At least on my end it seems to be working perfectly now using the latest v1.17 branch:

image

**Comment by nefarius** [comment]
This has been superseded by the changes introduced in v1.17.333.

**Pull request closed without merging**
